* org-epub

Generate =.epub= files directly from OrgMode. This will export EPUB
version 2, which should give broad compatibility. It should also be
relatiely easy to convert the resulting =.epub= to a =.mobi= (Kindle).

** Prerequisites

This depends on Emacs 25 and OrgMode 9, it won't work on OrgMode 8 or
any version of Emacs before 25.

** Usage

Use org-epub like this:

#+BEGIN_EXAMPLE
(setq org-publish-project-alist
      '(

	("reader-1"
	 :base-directory "~/org-bjcp/"
	 :base-extension "org"
	 :publishing-directory "~/bjcp-epub/reader1/"
	 :recursive t
	 :publishing-function org-epub-publish-to-epub
	 :headline-levels 4
	 :auto-preamble t
	 :preparation-function org-epub-publish-finish
         ;; epub specific - these *MUST* be set
	 :epub-file "bjcp.epub"
	 :author "Beer Judge Certification Program"
	 :publisher "Mark Meyer"
	 :rights "t.b.d."
	 :toc-depth 2
	 :uid "http://ofosos.org/bjcp/jpm.epub"
	 :title "Beer Judge Prep - Reader 1"
	 :language "en"
	 :subject "non-fiction beer"
	 :description "Beer Judging Prep Class, Reader for Session One"
	 :epub-date "2017-01-01"
	 )

	))
#+END_EXAMPLE

Then =M-x org-publish RET bjcp RET=. Should work reasonably.

After that you'll have an output directory with all the important
files. Change to that directory:

#+BEGIN_EXAMPLE
$ zip -X0 target.epub mimetype
$ zip -Xur9D target.epub META-INF content.opf toc.ncx *.html
#+END_EXAMPLE

That should give you a working =target.epub= file.

** Caveats

These will eventually be fixed:

 - Stylesheets not implemented.
 - Can't have space or anything special in your filenames.
 - No cover page/art possible
 - Part headings are not included
 - Headline levels are borken
 - Implement zipping
