* ox-epub

Generate =.epub= files directly from OrgMode. This will export EPUB
version 2, which should give broad compatibility. It should also be
relatiely easy to convert the resulting =.epub= to a =.mobi= (Kindle).

** Prerequisites

This depends on Emacs 24.3 and OrgMode 9, it won't work on OrgMode 8 or
any version of Emacs before 24.3.

** Installation

=M-x package-install RET ox-epub RET=

** Usage

Hit =C-c C-e E e= to publish the current buffer to an EPUB.

There are some required export options that need to be set. These are

 - =UID= a unique id of the document, otherwise known as uri, may be a url
 - =DATE= the date of the document, for valid values see
   [[https://www.w3.org/TR/NOTE-datetime]]
 - =AUTHOR= the document author or editor, the creator in the EPUB spec
 - =TITLE= the document title

Furthermore there are some properties which are optional:

 - =Subject= the subject matter of the book
 - =Description= a description of the book
 - =Publisher= the publisher of the book
 - =License= the rights associated with this book, the copyright
   notice and further rights may be included in this option.

The only other option that is exported:

 - =LANGUAGE= the language of the book, this is to be interpreted
   according to RFC3066 or it's succeeding documents
   [[https://www.ietf.org/rfc/rfc3066.txt]], no other interpretations are
   allowed according to the EPUB spec.

** Features

Currently =ox-epub= can do the following:

 - simple cover images (broken)
 - direct =.epub= generation

** Caveats

These will eventually be fixed:

 - Stylesheets not implemented.
